### PR TITLE
modified: #356 searchall

### PR DESCRIPTION
**Pull request by shuomikan**
because slow network(GFW, so I must use local data

### CODE REVIEW

**Comment by svnpenn** [comment]
If you want to search local data, why not just use `apt-cyg search`?

**Comment by shuomikan** [comment]
that's not search installed packages?
I want search other package in setup.ini of mirror

**Comment by svnpenn** [comment]
This patch makes no sense. You've shanghaied `apt-cyg searchall` when really you patch is closer to `apt-cyg list` or `apt-cyg show`. You should perhaps elaborate on why your patch is better than any of these.

**Comment by shuomikan** [comment]
No,no.My English is not good.Bring to you the trouble really sorry
I want search all available packages, but it is too slow. I want a faster rate.
and it return value is many not necessary.
e.g
the raw
$ ./apt-cyg searchall git
--2015-01-17 15:00:47--  http://cygwin.com/cgi-bin2/package-grep.cgi?text=1&arch=x86_64&grep=git
正在解析主机 cygwin.com (cygwin.com)... 209.132.180.131
正在连接 cygwin.com (cygwin.com)|209.132.180.131|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：未指定 [text/plain]
正在保存至: “matches”

matches                        [  <=>                                     ]  16.28K  43.3KB/s 用时 0.4s

2015-01-17 15:01:25 (43.3 KB/s) - “matches” 已保存 [16673]

WindowMaker
afio
audiofile
copyright-update
cvs2svn
cygport
cygwin-doc
cygwin32-w32api-headers
db-doc
ddir
emacs
emacs-el
email
figlet
fish
flac-docs
git
git-completion
git-cvs
git-email
git-gui
git-review
git-svn
gitk
gitweb
grace
guilt
libQt5Core-devel
libQt5Svg-devel
libQt5XmlPatterns-devel
libQtSvg4-devel
libaudiofile-devel
libaudiofile1
libboost-devel
libdatrie
libdatrie-devel
libdatrie-doc
libdatrie1
libggi2-samples
libgirepository1.0-devel
lyx
makeself
mc
mercurial
mingw64-i686-headers
mingw64-x86_64-headers
netpbm
ngspice
octave
octave-doc
octave-signal
odt2txt
offlineimap
orage
perl
pl
pngcrush
pngquant
pwget
python
python-paramiko
python-pyqt4
python-pyqt5
python3
python3-doc
python3-pyqt4
python3-pyqt5
qt3-doc
qt4-doc
qt5-base-doc
qt5-base-examples
qt5-svg-doc
quilt
rpm
ruby-bcrypt
ruby-bigdecimal-doc
ruby-bundler
ruby-bundler-doc
ruby-doc
ruby-jquery-rails
ruby-json
ruby-mail-doc
ruby-railties
ruby-rdoc-doc
ruby-sass-rails
ruby-sdoc
ruby-sdoc-doc
ruby-test-unit-doc
ruby-tzinfo-doc
ruby-unicorn
ruby-unicorn-doc
rubygems
rubygems-doc
rxvt-unicode
splitpatch
stgit
subversion-devel
tailor
tcl
tesseract-ocr
texlive-collection-binextra
texlive-collection-binextra-doc
texlive-collection-context
texlive-collection-fontsextra
texlive-collection-fontsrecommended
texlive-collection-fontutils
texlive-collection-langarabic
texlive-collection-langcjk
texlive-collection-langcyrillic
texlive-collection-langgreek
texlive-collection-langindic
texlive-collection-langitalian
texlive-collection-langjapanese
texlive-collection-latexextra
texlive-collection-latexextra-doc
texlive-collection-latexrecommended
texlive-collection-metapost-doc
texlive-collection-xetex
tig
vim-common
w32api-headers
wput
xclock
xfig-lib
xkeyboard-config
xlsx2csv
zsh
start --2015-01-17 15:00:47 end 2015-01-17 15:01:25 (43.3 KB/s)
my patch
$ apt-cyg searchall git
git
     "Distributed version control system"
git-completion
     "Bash completion for Git version control system"
git-cvs
     "CVS compatibilty support for Git version control system"
git-debuginfo
     "Debug info for git"
git-email
     "Email tools for Git version control system"
git-gui
     "Graphical interface for Git version control system"
git-review
     "Tool to submit code to Gerrit"
git-svn
     "Subversion compatibility support for Git version control system"
gitk
     "Git repository browser"
gitweb
     "Web interface for Git version control system"
stgit
     "Quilt functionality on top of git"
texlive-collection-langitalian
     "TeX Live italian language support"

**Pull request closed without merging**
