### PR TITLE
Created auto completion script

### PR DESCRIPTION
**Pull request by VarunAgw**
It definitely is not the fastest way, but it works

### CODE REVIEW

**Comment by svnpenn** [comment]
Isnt this a syntax error:

    suggested_packages=$suggested_packages | $(tr '\n' ' ')

**Comment by VarunAgw** [comment]
It is working fine for me. Have you tried installing it?

**Comment by svnpenn** [comment]
@VarunAgw I have never seen that syntax. You need to explain what that line is doing.

**Comment by VarunAgw** [comment]
@svnpenn `$suggested_packages` are newline separated values. It converts new lines to space

**Comment by svnpenn** [comment]
@VarunAgw no it doesnt:

    #!/bin/sh
    alpha='bravo
    charlie
    delta
    '
    foxtrot=$alpha | $(tr '\n' ' ')
    echo alpha
    echo "$alpha"
    echo foxtrot
    echo "$foxtrot"

Output:

    alpha
    bravo
    charlie
    delta

    foxtrot

You see, with my example you code fucks up *foxtrot* and turns it into an empty
string. I am closing this pull request. If you can prove what that line does
with an isolated example, I will reopen.

**Comment by VarunAgw** [comment]
@svnpenn 

Yeah! Sorry you were right. I am new to shell programming and it was somehow working so I didn't noticed the syntax error. Anyway I have fixed the syntax error in https://github.com/VarunAgw/apt-cyg/commit/f4fcca521132c7d83a8f8e5faa3445aeaa7f3abb

What do you say? 

Btw since code is slow and not of high quality, you are free to not merge it into main repository.

**Comment by svnpenn** [comment]
The code is decent enough, however I am really am not interested in merging this. If more people comment in support I will reconsider. Until then, people can get like this:

    git clone git://github.com/transcode-open/apt-cyg
    git pull origin pull/67/head

**Pull request closed without merging**
